title: The Interesting Times
email: your-email@example.com
description: May you come up with an interesting description
baseurl: ''
url: ''
google_analytics: UA-131540516-1
twitter_username: jekyllrb
github_username: jekyll
excerpt_separator: <!--more-->
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections_dir: _collections
collections:
  columns:
    output: true
  heros:
    output: true
twitter: twitter
github: github
linkedin: linkedin
facebook: facebook
